cookie:
  expiry_days: 30
  key: super_secret_key
  name: session_cookie_name
credentials:
  usernames:
    almacen:
      email: app+almacen@mywero.com.co
      failed_login_attempts: 0
      logged_in: false
      name: Almacen
      password: $2b$12$mAoI9Q/0T1Wn0hy65fwFN.CpaUA15dbPgUVDT7XATWEmtKFHIo8sy
      role: caracol_users
    mantenimiento:
      email: app+mantenimiento@mywero.com.co
      failed_login_attempts: 0
      logged_in: false
      name: Mantenimiento
      password: $2b$12$juBp/hgBiZk0rcnymWIWi.yUj/97G7/FAA99Iqa2B4FQ1tcodJAF2
      role: caracol_users
    sedes:
      email: app+sedes@mywero.com.co
      failed_login_attempts: 0
      logged_in: false
      name: Sedes
      password: $2b$12$oOrI/cKM0KAtclKHmSLumez.tsM8LzDUSjVPy2rUBOocu8qilVbSy
      role: caracol_users
    sostenibilidad:
      email: app+sostenibilidad@mywero.com.co
      failed_login_attempts: 0
      logged_in: true
      name: Sostenibilidad
      password: $2b$12$4rUb5H8kGHxrR8jVu60OQOPRbvRVgY9zdL9tn.OO.QDhQcrq0gNsy
      role: caracol
    sst:
      email: app+sst@mywero.com.co
      failed_login_attempts: 0
      logged_in: false
      name: SST
      password: $2b$12$34mFitoSZ51UnRSu/HeCP.DklzSWKing2xzK.Xhyy91DQWW2WY4du
      role: caracol_users
    ti:
      email: app+ti@mywero.com.co
      failed_login_attempts: 0
      logged_in: false
      name: Ti
      password: $2b$12$SX/BYQ2QznCNNMTacMtDduFqtf5lhKf6YBE8vslokLWHIrldMY42e
      role: caracol_users
    wero-caracol:
      email: app+wero-caracol@mywero.com.co
      failed_login_attempts: 0
      logged_in: true
      name: Wero Caracol
      password: $2b$12$OUpzEiOMAe0OUW9iiW5ChO9bc6dqnHvPlV3knlrYRrD7jE984wIh6
      role: wero
preauthorized:
  emails:
  - melsby@gmail.com
