cookie:
  expiry_days: 30
  key: somesignaturekey
  name: cookie_name
credentials:
  usernames:
    acoplasticos:
      email: acoplasticos@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Acoplasticos
      password: $2b$12$gfV/ny1JwjoJUd1GjXv06euklMLyqYbg3sDl9U3/lEesDro3XRGHe
      role: admin
    wero:
      email: wero@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Wero
      password: $2b$12$JtGhOwtOMttoDISYQwy9zenCwU16Z7vdpti39463IK/.uP75HeVWm
      role: user
    wero-caracol:
      email: wero@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Wero Caracol
      password: $2b$12$LNs921eIyRPTrxEchDYbnuA/FernrU4NHNFrhMaRMZTs3HJGQzHmq
      role: wero
    caracol:
      email: wero@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Caracol
      password: caracol123
      role: caracol
    almacen:
      email: wero@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Almacen
      password: almacen123
      role: caracol_users
    enfermeria:
      email: wero@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Enfermeria
      password: enfermeria123
      role: caracol_users
    mantenimiento:
      email: wero@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Mantenimiento
      password: mantenimiento123
      role: caracol_users
    sedes:
      email: wero@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Sedes
      password: sedes123
      role: caracol_users
    ti:
      email: wero@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Ti
      password: ti123
      role: caracol_users
    wero2:
      email: wero@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Wero2
      password: $2b$12$8qqQb84ylw2SyEpNtjHum.hEZoiPXdx/w8YxX0bjeh0IVFuix6JpO
      role: user2
preauthorized:
  emails:
  - melsby@gmail.com
